apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: dev-

commonLabels:
  env: development
  managed-by: argocd

patches:
  - target:
      kind: Deployment
      name: tnext
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
