apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami-app
  namespace: argocd
spec:
  project: tnext
  source:
    repoURL: https://github.com/telematiq/tnext_config.git
    targetRevision: HEAD
    path: apps/whoami
  destination:
    server: https://kubernetes.default.svc
    namespace: whoami-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
