apiVersion: v1
kind: Service
metadata:
  name: tnext
  labels:
    app: tnext
    tailscale.com/expose: "true"
spec:
  type: ClusterIP
  selector:
    app: tnext
  ports:
    - name: http
      port: 80
      targetPort: 5678
